{% set name = "pyiceberg" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiceberg-{{ version }}.tar.gz
  sha256: 0e79b5b59a1cbe5183a69c6b759b78ebdbb8611dfeb1b984d048625077b983ba

build:
  entry_points:
    - pyiceberg = pyiceberg.cli.console:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry
  run:
    - python >=3.7,<4.0
    - click >=8.0.0,<9.0.0
    - fsspec >=2022.8.2
    - mmh3 >=3.0.0,<4.0.0     # pip uses mmhash3
    - pydantic >=1.10.2,<2.0.0
    - pyyaml >=5.0.0,<7.0.0
    - requests >=2.28.1,<3.0.0
    - rich >=12.5.1,<13.0.0
    - zstandard >=0.18.0,<0.19.0
    - pyarrow
    - pyparsing
    - hive-thrift-py
    - thrift
    - botocore
    - s3fs
    - boto3

test:
  imports:
    - fb303
    - hive_metastore
    - pyiceberg
  commands:
#    - pip check
    - pyiceberg --help
  requires:
    - pip

about:
  home: https://iceberg.apache.org/
  summary: Apache Iceberg is an open table format for huge analytic datasets
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
