{% set name = "pyiceberg" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiceberg-{{ version }}.tar.gz
  sha256: d9e8d1badb576472bd10ccad3ccfdd193027a1892c493e6bb04ed61d8fb57458

build:
  entry_points:
    - pyiceberg = pyiceberg.cli.console:run
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - wheel
    - cython >=3.0.0
    - setuptools
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - mmhash3 >=3.0.0,<4.0.0
    - mmh3 >=3.0.0,<4.0.0     # pip uses mmhash3
    - requests >=2.20.0,<3.0.0
    - click >=7.1.1,<9.0.0
    - rich >=10.11.0,<14.0.0
    - strictyaml >=1.7.0,<2.0.0
    - pydantic >=2.0,<3.0,!=2.4.0,!=2.4.1
    - sortedcontainers ==2.4.0
    - fsspec >=2023.1.0,<2024.1.0
    - pyparsing >=3.1.0,<4.0.0
    - zstandard >=0.13.0,<1.0.0
  run_constrained:
    # https://github.com/apache/iceberg-python/blob/main/pyproject.toml#L60C1-L60C59
    - pyarrow >=9.0.0,<15.0.0
    - pandas >=1.0.0,<3.0.0
    - duckdb >=0.5.0,<1.0.0
    - ray >=2.0.0,<3.0.0
    - python-snappy >=0.6.0,<1.0.0
    - thrift >=0.13.0,<1.0.0
    - boto3 >=1.24.59
    - s3fs >=2023.1.0,<2024.1.0
    - adlfs >=2023.1.0,<2024.1.0
    - gcsfs >=2023.1.0,<2024.1.0
    - psycopg2-binary >=2.9.6
    - sqlalchemy >=1.4.0,<3.0.0

test:
  imports:
    - fb303
    - hive_metastore
    - pyiceberg
  commands:
    - pip check
    - pyiceberg --help
  requires:
    - pip

about:
  home: https://iceberg.apache.org/
  summary: Apache Iceberg is an open table format for huge analytic datasets
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
